config:
    required: true

database:
    +:
        name: default
        namespace: Creonit\StorageBundle\Model
        defaultIdMethod: native

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk

    storage_data_entry:
        item_name: varchar(255) key(20)
        locale: varchar(10) key(2)
        context: varchar(255) key(10)
        visible: bool = 1
        +behavior:
            - sortable: {use_scope: 'true', scope_column: 'item_name'}
            - timestampable

    storage_data_field:
        storage_data_entry_id: int > storage_data_entry.id
        field_name: varchar(255) key(10)
        locale: varchar(10) key(2)
        value: longvarchar
        +behavior:
            - timestampable