services:
    _defaults:
        autowire: true
        autoconfigure: true

    Creonit\StorageBundle\Event\EventSubscriber:

    Creonit\StorageBundle\Storage\Storage:
        public: true

    Creonit\StorageBundle\Storage\StorageVariable:
        public: true